# Project ID from the Supabase dashboard
project_id = "xqwhbkmzxtcnbbhmyxwl"

# Edge Functions configuration
[functions]
[functions.payments-webhook]
verify_jwt = false

[functions.create-checkout]
verify_jwt = true

[functions.get-plans]
verify_jwt = false